# Generated by Django 3.1.3 on 2020-11-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201128_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcategory',
            name='bc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.branchcategory'),
        ),
    ]
