# Generated by Django 3.1.3 on 2020-12-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201203_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchcategory',
            old_name='bc_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_type',
            new_name='branch_type',
        ),
    ]
