# Generated by Django 3.1.3 on 2020-12-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_remove_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytype',
            name='branch_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='categorytype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='type.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='type.categorytype'),
        ),
    ]
